;;; snippets.el -*- lexical-binding: t; -*-
(defun yas-reindented-selected-text (indent)
  (when-let* ((text (yas-selected-text))
              (lines (split-string text "\n"))
              (non-empty (seq-filter (lambda (l) (string-match "[^ \t]" l)) lines))
              (min-indent (apply #'min
                                 (mapcar (lambda (l)
                                           (string-match "[^ \t]" l))
                                         non-empty)))
              (prefix (make-string indent ?\s)))
    (mapconcat (lambda (l)
                 (if (>= (length l) min-indent)
                     (concat prefix (substring l min-indent))
                   l))
               lines "\n")))

(defun yas-wrap-region ()
  (interactive)
  (when (region-active-p)
    (let ((beg (save-excursion (goto-char (region-beginning))
                               (line-beginning-position)))
          (end (save-excursion (goto-char (region-end))
                               (line-end-position))))
      (set-mark beg)
      (goto-char end)))
  (yas-insert-snippet))

(defun yas-body (indent)
  (or (yas-reindented-selected-text indent)
      (make-string indent ?\s)))
