name: test

on:
  push:
  pull_request:

jobs:
  ert:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs: ["29.4", "30.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs }}
      - run: bin/test
      - name: byte-compile check (warnings only)
        run: bin/compile-check
        continue-on-error: true
